@startuml
skinparam monochrome true
object RoomData
object Track
object Album
object Artist
object CommandMessage
object CommandMessageQueue
object TrackQueue
object PlayerState

RoomData "1"--*"1" TrackQueue
RoomData "1"--* "0.." Track
RoomData "1" --* "1" CommandMessageQueue
CommandMessageQueue "1" --o "0.." CommandMessage
TrackQueue "1"--o "0.." Track
' TrackHistory "1" --o "0.." Track
RoomData "1" --* "1" PlayerState
Track "1" --o "1.." Artist
Track "1" --o "1" Album

@enduml