@startuml
skinparam monochrome true
object Qdio
object Track
object Album
object Artist
object CommandMessage
object CommandMessageQueue
object TrackQueue
object PlayerState

Qdio "1"--*"1" TrackQueue
Qdio "1"--* "0.." Track
Qdio "1" --* "1" CommandMessageQueue
CommandMessageQueue "1" --o "0.." CommandMessage
TrackQueue "1"--o "0.." Track
' TrackHistory "1" --o "0.." Track
Qdio "1" --* "1" PlayerState
Track "1" --o "1.." Artist
Track "1" --o "1" Album

@enduml