@startuml
package communication
package information
package model
package playback
package room
package view

room --> information
room --> model
room --> communication
room --> playback
communication -> model
information -> model
playback -> model
playback .> information

view ..> room
view ..> playback
view ..> information
view ..> model

@enduml
